### DISCUSSION TITLE
Improving syntax+documentation

### DISCUSSION THREAD

**Discussion by Clancy508** [coreos/ignition#2095] [General]
Hi all, I'm wondering if there's any work ongoing to tidy up the syntax for ignition and the documentation? At least for Fedora CoreOS I've noticed it's not particularly clear from the published specifications when a subheading requires a leading hyphen, for instance, and in at least one case this is inconsistent between equivalent uses, e.g. for setting file content using `content:` vs `append:` (note the hyphen and extra indentation on the append inline - transpilation throws an error without this even though the contents example works perfectly):

```
- path: /some/file/path
  contents:
    inline: |
      New
      File
      Contents
```

vs

```
- path: /some/existing/file
  append:
    - inline: |
        Added File Contents
```
