### ISSUE TITLE
RFE: Introduce a general object for data that can be reused in the specification

### ISSUE THREAD

**Issue by eriksjolund** [coreos/ignition#1097]
I noticed at
https://github.com/coreos/fcct/blob/master/docs/configuration-v1_1.md
that __systemd__ -> __contents__ does not have variant for including the contents from a local file. For me it would have been convenient to have that feature.

Why not generalize the data input, so that strings and bytearrays always can be included from URLs, local files or inline?
Something like two new "datatypes":
__general_text_data__ and __general_binary_data__

 Just a sketch:

  * **_general_text_data_** (object): the config that will replace the current.
    * **_source_** (string): the URL of the config. Supported schemes are `http`, `https`, `s3`, `tftp`, and [`data`][rfc2397]. Note: When using `http`, it is advisable to use the verification option to ensure the contents haven't been modified. Mutually exclusive with `inline` and `local`.
    * **_inline_** (string): the contents of the config. Mutually exclusive with `source` and `local`.
    * **_local_** (string): a local path to the contents of the config, relative to the directory specified by the `--files-dir` command-line argument. Mutually exclusive with `source` and `inline`.
    * **_http_headers_** (list of objects): a list of HTTP headers to be added to the request. Available for `http` and `https` source schemes only.
      * **name** (string): the header name.
      * **_value_** (string): the header contents.
    * **_verification_** (object): options related to the verification of the config.
      * **_hash_** (string): the hash of the config, in the form `<type>-<value>` where type is either `sha512` or `sha256`.

If it would be possible to reference the string contents of one of 

__passwd__ -> __users__ -> __ssh_authorized_keys__

with a __general_text_data__, you could start referencing your public ssh key from Github, as they are downloadable like this

```
wget https://github.com/eriksjolund.keys
```

**Comment by bgilbert** [comment]
Okay, I've moved the issue over to Ignition.

We already have a reusable data type for this, `Resource`, which you can see in action e.g. [here](https://github.com/coreos/ignition/blame/master/docs/configuration-v3_2_experimental.md#L82-L89).  Expanding every field to use Resource would be a major breaking change and would make configs much more verbose.  If you have a set of use cases where this would be really helpful, though, please do share them here.

**Comment by bgilbert** [comment]
You can also use the `files` section to write services and SSH keys:

```yaml
variant: fcos
version: 1.1.0
storage:
  directories:
    - path: /home/core/.ssh
      user:
        name: core
      group:
        name: core
      mode: 0700
    - path: /home/core/.ssh/authorized_keys.d
      user:
        name: core
      group:
        name: core
      mode: 0700
  files:
    - path: /home/core/.ssh/authorized_keys.d/github
      user:
        name: core
      group:
        name: core
      mode: 0600
      contents:
        source: https://github.com/bgilbert.keys
    - path: /etc/systemd/system/example.service
      contents:
        source: https://example.com/example.service
systemd:
  units:
    - name: example.service
      enabled: true
```

**Comment by eriksjolund** [comment]
### List of use cases
#### Use case 1. Including a systemd unit file from the file system

It seems to be addressed in
https://github.com/coreos/ignition/pull/986
that  @bgilbert mentioned in
https://github.com/coreos/ignition/issues/1097#issuecomment-688981237


This use case can also be worked around by using 
__storage -> files -> contents -> local__

I did that in an experiment of mine
https://github.com/Clinical-Genomics/scout/blob/systemd_services_podman/systemd/scout.fcc

```
storage:
  files:
    - path: /home/core/.config/systemd/user/scout-pod.service
      user:
        name: core
      group:
        name: core
      mode: 0644
      contents:
        local: scout-pod.service
```
(although that example uses systemd user units)

#### Use case 2. Being able to specify an SSH public key as an URL
 
Being able to specify an URL, it would be easier to identify the person being granted access just by looking
at an Ignition/FCC file.
For instance URL:s could be used in the form of _https://github.com/<githubusername\>.keys_ 

@bgilbert Yes, your suggestion in https://github.com/coreos/ignition/issues/1097#issuecomment-700164654 to use 
__storage -> files -> contents -> source__
would solve that. 

### Some more thoughts

My first thought by creating this RFE was that over time there will always pop up RFE:s  requesting conversion of a string datatype into the `Resource` datatype in the spec. For every such change the spec would break. To avoid that situation,
why not right away change all occurrences of the string datatype into the general  `Resource` datatype?

I've been thinking a bit more about this RFE. As there are workarounds, I don't have such a big need for it. If you want you could close this issue, or just keep it open to gather user feedback.
