### ISSUE TITLE
SSH certificate authority support

### ISSUE THREAD

**Issue by Okeanos** [coreos/ignition#1174]
# Feature Request #

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?

Any

## Desired Feature ##

I would very much like it if ignition (and subsequently fcct/Fedora CoreOS) would natively support SSH certificate authorities. Currently the ignition spec supports a `security` declaration with custom certificate authorities for `tls` as well as a user specific declaration for individual `sshAuthorizedKeys`. Sadly, there is no built in way to roll out a SSH CA onto a machine with ignition.

Having the ability to roll out an SSH certificate authority with ignition would greatly simplify SSH key management and deployment of machines (especially with the same canonical name). The dreaded host key verification dialog would thus be a thing of the past because a client could verify authenticity of the remote machine by virtue of the given certificate signed by a mutually trusted CA.

## Other Information ##

This might be slightly icky because the host keys would have to be supplied alongside the host certificates via ignition because I don't see that injecting the signing authority certificate into the boot process to sign randomly generated certificates is a good idea.

For more information SSH CAs see e.g.:

- https://www.lorier.net/docs/ssh-ca.html
- https://jameshfisher.com/2018/03/16/how-to-create-an-ssh-certificate-authority/
- https://smallstep.com/blog/use-ssh-certificates/
- https://ibug.io/blog/2019/12/manage-servers-with-ssh-ca/

**Comment by bgilbert** [comment]
You can use Ignition's `storage.files` section to write SSH host keys and sshd configuration.  For the latter, you can append to `/etc/ssh/sshd_config` (not recommended) or, with newer versions of sshd and appropriate distro-side configuration (e.g. on Fedora CoreOS), you can write a config fragment into `/etc/ssh/sshd_config.d/*.conf`.  It might be useful to add FCCT sugar which does this configuration for you; what config directives would you like to see?

(We usually support specific host features via FCCT sugar, rather than directly in Ignition.  The two cases you mentioned are special: `ignition.security.tls.certificateAuthorities` section affects the CAs Ignition itself uses for HTTPS connections, and `sshAuthorizedKeys` is a convenience for writing keys to individual user directories with appropriate permissions.)

**Comment by Okeanos** [comment]
You note concerning FCCT sugars makes sense and didn't even occur to me when I wrote the ticket, thanks.

Concerning the missing (so to speak) directives to conveniently support SSH CAs I suppose something like the following might make sense (using fcct wording):

```yaml
ignition:
  config:
    security:
      ssh:
        certificate_authority:
          # This entry should create a matching "TrustedUserCAKeys /etc/ssh/<NAME>.pub" in /etc/ssh/sshd_config and also create the file at "/etc/ssh/<NAME>.pub"
          authority:
            name: # string
            certificate: # one of compression, source, inline, local
          host_keys: # Each entry here should ceate a matching "HostCertificate /etc/ssh/ssh_host_<TYPE>_key-cert.pub" entry in /etc/ssh/sshd_config I believe
            - type: rsa # (ssh key types)
              key: 
                contents: # one of compression, source, inline, local
              certificate:
                contents: # one of compression, source, inline, local

```

There's a couple of other attributes etc. (such as `AuthorizedPrincipalsFile` and `RevokedKeys`) but I don't have the time right now to give a "full" spec for that … I can try to improve the example above later on if it is of interest to you.
