### ISSUE TITLE
Clevis bind warning: Value 512 is outside of the allowed entropy range, adjusting it.

### ISSUE THREAD

**Issue by rugk** [coreos/ignition#1192]
# Bug #

## Operating System Version ##

Fedora 33 Workstation

## Ignition Version ##

`fedora-coreos-33.20210328.3.0-metal.x86_64` (dunno what’s included there, likely the latest)

## Environment ##

bare metal

## Expected Behavior ##

This _warning_ for entropy is not shown. This is scary.

The error I also see is “Unable to fetch advertisement”, but that is obvious and actually intentionally triggered for this bug report. (i.e. no network connectivity)

## Actual Behavior ##

Ignition reports STDERR output for `clevis luks bind -f  -k /somekeyfile/root -d “…/by-partlabel/root” “sss” “some-json”`:
> Warning: Value 512 is outside of the allowed entropy range, adjusting it.

…in addition to the mentioned other error.

## Reproduction Steps ##

Use a YAML to wipe and [encrypt the root partition / and expand it e.g.](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_sizing_the_root_partition):

```yaml
variant: fcos
version: 1.3.0
# ...
luks:
    # encrypted root
    - name: root
      label: luks-root
      device: /dev/disk/by-partlabel/root
      clevis:
        tpm2: false
        threshold: 1
        tang:
          - url: # ...
            thumbprint: # ..
      wipe_volume: true
```

Now, in my case there was a real error. You need to trigger one, (in my case by an inaccessible URL) , so just set [`url`] to some non-existent server or just plug out the ethernet cable. :sweat_smile: 

Just install it:
```
$ sudo coreos-installer install /dev/sdd -i ignition/[…].ign --image-file downloads/fedora-coreos-33.20210328.3.0-metal.x86_64.raw.xz --delete-karg 'console=ttyS0,115200n8'
```

And boot.

## Other Information ##

BTW I have no idea what clevis now actually adjusted and to which value… it did not mentioned that. :laughing: (should possibly also be improved)
