### ISSUE TITLE
No network (IPv4?) connectivity via Ethernet at first boot for LUKS/Clevis setup

### ISSUE THREAD

**Issue by rugk** [coreos/ignition#1201]
# Bug #

## Operating System Version ##

Fedora CoreOS 33

## Ignition Version ##

Don’t know. What’s included in fedora-coreos-33.20210328.

## Environment ##

Bare metal. fedora-coreos-33.20210328

## What I did ##

Use a YAML to wipe and [encrypt the root partition / and expand it e.g.](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_sizing_the_root_partition) and setup the encryption via clevis with a tang server:

```yaml
variant: fcos
version: 1.3.0
# ...
luks:
    # encrypted root
    - name: root
      label: luks-root
      device: /dev/disk/by-partlabel/root
      clevis:
        tpm2: false
        threshold: 1
        tang:
          - url: # ...
            thumbprint: # ..
      wipe_volume: true
```

Just installed it directly to the boot disk:
```
$ sudo coreos-installer install /dev/sdd -i ignition/[…].ign --image-file downloads/fedora-coreos-33.20210328.3.0-metal.x86_64.raw.xz --delete-karg 'console=ttyS0,115200n8'
```

And booted.

## Actual Behavior ##

Now, however, when booting it all works fine until Clevis tries to contact the Tang server for the encryption key for LUKS.
Strangely I get an network error.

Ignition reports STDERR output for `clevis luks bind -f  -k /somekeyfile/root -d “…/by-partlabel/root” “sss” “some-json”`:
> Unable to fetch advertisement: [url] 
> Invalid input!

It also [reports one more warning](https://github.com/coreos/ignition/issues/1192), which is likely not related though and clearly a bug or so.

## Expected Behavior ##

LUKS/Clevis should be able to fetch the config from the network and at least Ethernet configuration should work… 

## Troubleshooting

Actually, in the emergency shell I discovered that I cannot `curl` to any URL or so, so it clearly has no networking.

The device is connected via an Ethernet cable, so that should™ work. Additionally, I should say **when using the “live system”**, i.e. just booting from an USB with the default ignition file, **it actually also does work**. There, I can also use `nmcli` etc., but this does not work in the emergency shell apparently…

So I just used `ip` and it indeed shows (only) IPv6 adresses hmm… :thinking: 
Note my Tang server URL is an IPv4 address.

![coreos-no-network|690x348](https://aws1.discourse-cdn.com/business4/uploads/fedoraproject/original/2X/7/79e3a9da220273c60fd5f30914292bf332c1583a.jpeg) 

(Sorry for the image I tried to mount an attached USB drive, but could not find the correct `/dev/…` device, at least there was no `/dev/sd*`.)

Also note the LEDs at the network adapter look well (yellow top left is constantly on; green top right is slowly blinking at regular intervals).

---

Also asked in the Fedora forum: https://discussion.fedoraproject.org/t/no-network-ipv4-connectivity-via-ethernet-at-first-boot-for-luks-clevis-setup/29260?u=rugk
