### ISSUE TITLE
LUKS device reported as wrong type even though type is set correctly

### ISSUE THREAD

**Issue by rugk** [coreos/ignition#1209]
# Bug #

Background information:
https://discussion.fedoraproject.org/t/how-to-mount-re-use-an-existing-luks-volume/29767?u=rugk

## Operating System Version ##
FCOS 34
fedora-coreos-34.20210503.1.1-live.x86_64

## Ignition Version ##
2.9.0

## Environment ##

bare-metal

## Expected Behavior ##

Do not report this error.

Or report a more detailed error, at least?

## Actual Behavior ##

I get the error that the volume is not of the correct type;
https://github.com/coreos/ignition/blob/0cbe33fee45d012515479a88f0fe94ef58d5102b/internal/exec/stages/disks/luks.go#L203-L204

> volume at "" is not of correct type, label, or UUID (found crypto_LUKS, "luks-external", [some uuid]) and a volume wipe was not requested

I guess this is wrong, see below.

## Reproduction Steps ##

```yml
variant: fcos
version: 1.3.0
storage:
  luks:
    # external disk
    - name: external
      label: luks-external
      device: /dev/disk/by-id/[…]:0-part1
      clevis:
        tpm2: false
        threshold: 1
        tang:
          - url: # ....
      wipe_volume: false
``` 

## Other Information ##

I explicitly set the correct LUKS label, as you can see when I `luksDump` the resource:
```
sudo cryptsetup luksDump /dev/sdc1                    
LUKS header information
Version:       	2
Epoch:         	6
Metadata area: 	16384 [bytes]
Keyslots area: 	16744448 [bytes]
UUID:          	46*******d1f
Label:         	luks-external
Subsystem:     	(no subsystem)
Flags:       	(no flags)
```

AFAIK the code goes in here [from here](https://github.com/coreos/ignition/blob/5290df52c8762119cf6fd0f612f8b8aaf5270b80/internal/exec/stages/disks/luks.go#L344), [in here](https://github.com/coreos/ignition/blob/5290df52c8762119cf6fd0f612f8b8aaf5270b80/internal/exec/util/blkid.go#L74) and gets all information.

Given everything looks correct AFAIK, I guess ` checkLuksDeviceExists` somehow works improperly…

The only way, where it could fail may be when opening it with a keyfile – that [does not exist](https://github.com/coreos/ignition/blob/0cbe33fee45d012515479a88f0fe94ef58d5102b/internal/exec/stages/disks/luks.go#L375-L380).

However, if it cannot open the existing LUKS partition (why does not it try to use Clevis BTW? It is already configured but well…), **then it should report this as an error and not complain about the _type_ of the partition**.

Whether the device can be opened has nothing to do with what "type" (in whatever meaning) it is.

**Edit:** I should note the string `opening luks device` does not appear in my journalctl logs, so after all maybe my speculation at the end is wrong.

**Comment by arithx** [comment]
So the specific issue here is that Ignition cannot validate that a given clevis backed LUKS device matches the config. Purely being able to unlock a device is not sufficient to say that it's configured exactly as specified in the config.

I believe the current resolution for this bug will be either the modification of that error string or another error path with a more exact error string as the actual behavior here is expected.

**Comment by rugk** [comment]
Okay, so let's discuss that general thing in https://github.com/coreos/ignition/issues/1210.

However, I now tried specifying a keyfile that I know is sure unlockable for Ignition and get the same error – so maybe my speculation about the keyfile being the fault, is wrong after all?

```yaml
variant: fcos
version: 1.3.0
storage:
  luks:
    # external disk
    - name: external
      label: luks-external
      device: /dev/disk/by-id/[…]:0-part1
      # disabled, because MBR disk is not properly configured yet as this
      # device: /dev/disk/by-partlabel/external
      clevis:
        tpm2: false
        threshold: 1
        tang:
          - url: # […]
      # temporary key"file" i.e. password to unlock disk at provisioning step as clevis unlocking at provisioning is not yet supported
      # see https://github.com/coreos/ignition/issues/1210
      key_file:
        inline: |-
          ******************
      wipe_volume: false
 ```
 
 I know the password as a key-file I put into `******************` is a password I can enter to unlock the device (just added via `cryptsetup luksAddKey`). And I double-checked in the log output on the device, it appears correctly in the Ignition config (as `"{keyFile": {source: "data:,******************", "verification": {}}}`).
 I even gave care not to include a trailing newline there by using `|-` instead of `|`, see https://yaml-multiline.info/.

**Comment by rugk** [comment]
Wait, now I'm confused when comparing the source code.

I added this to my OP:
>  should note the string opening luks device does not appear in my journalctl logs, so after all maybe my speculation at the end is wrong.

However [even the first command is not logged](https://github.com/coreos/ignition/blob/1d56dc8e717a10c1a8b392050bcb3d269cd42154/internal/exec/stages/disks/luks.go#L326-L327) that checks whether that is a LUKS device? I.e. `checking if %v is a luks device`. Or is that another log level / only logged when a failure appears?

**Comment by rugk** [comment]
Also tried it without having a `label` specified, failed with the same error.

Uhm… I guess improving the error messages here (so that they show _what_ property is actually missing why it claims the type is wrong) would be useful.

**Comment by bgilbert** [comment]
Ignition is not currently designed to reuse existing Clevis-backed LUKS volumes; see https://github.com/coreos/ignition/issues/1210#issuecomment-841511969 for some additional context.  Since you don't actually want Ignition to modify the device, you don't need to specify the `storage.luks` section at all; just have Ignition write a line into `/etc/crypttab` with the `_netdev` flag set.

**Comment by rugk** [comment]
Okay fine, but anyway, the approach here should also work, should not it? After all reusing LUKS volumes (with a keyfile) _is_ implemented.

So, to eliminate this:
> Or does Ignition maybe improperly create key files with a line ending?

I now attached a keyfile to the LUKS volume with a line ending and it still does not work. So that's not the issue.

Still, something in  `checkLuksDeviceExists` has to be wrong.

Also how do I get these detailed command logs that appear in the source code (`.Logger.LogCmd`)? As explained, I don't see them in `journalctl`…

**Comment by bgilbert** [comment]
> Okay fine, but anyway, the approach here should also work, should not it? After all reusing LUKS volumes (with a keyfile) is implemented.

If your existing LUKS volume is only configured with a keyfile, it should work.  If it's also configured with Clevis unlocking, it won't work, since Ignition can't verify that the config matches the volume.

**Comment by rugk** [comment]
> If your existing LUKS volume is only configured with a keyfile, it should work.

It is. As explained I explicitly added a keyslot. And it does not work…

> If it's also configured with Clevis unlocking, it won't work

well… it is too, but that should not matter, should it?
It's just another keyslot.

I did not see it anywhere in the source code that Ignition would compare keyslots or so.

**Comment by rugk** [comment]
Okay, so I've removed all key slots, and kept only one remaining keyslot with a keyfile (respectively passphrase) that Ignition can unlock because it is given to it…

It **still does not work**. The LUKS device is now _exactly as specified_ (no Clevis included anymore, I `clevis unbind`'ed it), but it does not work.
And as said, from reading the source code I doubt Ignition actually verifies the LUKS keyslots.
And I verified in the emergency shell that `/run/ignition/luks-keyfiles/external` contains the passphrase I have set, correctly without any line-ending.

I still get the "wrong type" error.
And I still get the **correct** [`found %s at %q with uuid %q and label %q` message](https://github.com/coreos/ignition/blob/0cbe33fee45d012515479a88f0fe94ef58d5102b/internal/exec/stages/disks/luks.go#L195).

```
$ sudo cryptsetup luksDump /dev/sdd1       
LUKS header information
Version:       	2
Epoch:         	14
Metadata area: 	16384 [bytes]
Keyslots area: 	16744448 [bytes]
UUID:          	464[…]ded1f
Label:         	luks-external
Subsystem:     	(no subsystem)
Flags:       	(no flags)

Data segments:
  0: crypt
	offset: […] [bytes]
	length: (whole device)
	cipher: aes-xts-plain64
	sector: 512 [bytes]

Keyslots:
  0: luks2
	Key:        512 bits
	Priority:   normal
	Cipher:     aes-xts-plain64
	Cipher key: 512 bits
	PBKDF:      argon2i
	Time cost:  6
	Memory:     ******
	Threads:    4
	Salt:       ******
	            ******
	AF stripes: ******
	AF hash:    sha256
	Area offset:32768 [bytes]
	Area length:****** [bytes]
	Digest ID:  0
Tokens:
Digests:
  0: pbkdf2
	Hash:       sha512
	Iterations: ******
	Salt:       ****** 
	            ****** 
	Digest:    ******
	            ****** 
	            ****** 
	            ****** 
```

```yaml
variant: fcos
version: 1.3.0
storage:
  luks:
    # external disk
    - name: external
      label: luks-external
      device: /dev/disk/by-id/[…]:0-part1
      # disabled, because MBR disk is not properly configured yet as this
      # device: /dev/disk/by-partlabel/external
      clevis:
        tpm2: false
        threshold: 1
        tang:
          - url: # …
            thumbprint: # …
      # temporary key"file" i.e. password to unlock disk at provisioning step as clevis unlocking at provisioning is not yet supported
      # see https://github.com/coreos/ignition/issues/1210
      key_file:
        inline: |-
          ******
      wipe_volume: false
```
