### ISSUE TITLE
Mounting fails, because of non-directory component “/sysroot/mnt”

### ISSUE THREAD

**Issue by rugk** [coreos/ignition#1212]
# Bug #

## Operating System Version ##

`fedora-coreos-34.20210503.1.1-live.x86_64` - current next stream

## Ignition Version ##

2.9.0

## Environment ##

bare-metal 

## Expected Behavior ##

Mounting succeeds.

## Actual Behavior ##

The last line in the log of `journalctl -t ignition`, even after printing the whole Ignition config is:
> }CRITICAL : Ignition failed: Mount path "/sysroot//mnt/external" contains non-directory component "/sysroot/mnt"

BTW yes the `}` at the start is really there, as it is the end of the Ignition config output it does there and in this case it seems to merge with that message…

This results in:
> ignition-complete.target: Job ignition-complete.target/start failed with result 'dependency'.

Doing an ls on `/sysroot/mnt`, I can see this is somewhat correct as it's a symbolic link:
```
$ ls -la /sysroot/mnt
[…] /sysroot/mnt -> var/mnt
```

As you can see, it links to `var/mnt` (_without_ a leading slash! – ~~also wonder whether that's intended~~).

~~In any case, in my emergency dracut shell I at least also cannot see any `/var/mnt` directory…~~

**Edit:** Ah of course it's intended by rpm-ostree's file layout. However, in the link's target, i.e. `/sysroot/var` there is also only a `lib` folder, no other folder, i.e. no `mnt` it actually expects. 

## Reproduction Steps ##

```yml
variant: fcos
version: 1.3.0
storage:
  luks:
    # external disk (already exists!)
    - name: external
      label: luks-external
      device: /dev/disk/by-id/[…]:0-part1
      key_file:
        inline: |-
          ********
      wipe_volume: false
  filesystems:
    - path: /mnt/external
      device: /dev/mapper/external
      format: btrfs
      wipe_filesystem: false
      with_mount_unit: true
 ```

BTW the `filesystems` -> systemd service for mounting the file is filesystem is correctly generated. 

## Other Information ##

I continue my challenge to mount an existing LUKS drive from https://github.com/coreos/ignition/issues/1210 ([originally here](https://discussion.fedoraproject.org/t/how-to-mount-re-use-an-existing-luks-volume/29767?u=rugk))

FYI: When I then just reboot, it cannot even mount `/root` anymore, [which is basically just configured as in the doc here](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_sizing_the_root_partition) (I did not include that part in the config above): It cannot find `/dev/disk/by-label/root`.
