### ISSUE TITLE
Feature Request: Support for LVM on bare-metal installation

### ISSUE THREAD

**Issue by cgruver** [coreos/ignition#1289]
For provisioning OpenShift worker nodes on bare-metal that will also host Ceph storage, it would be nice to be able to configure Logical Volume Management via Ignition.

This would be in support of servers with multiple SSDs installed.

The implementation might be able to borrow from the methods used by Anaconda Kickstart:

For example:

```bash
part pv.1 --fstype="lvmpv" --ondisk=${disk1} --size=1024 --grow --maxsize=2000000
part pv.2 --fstype="lvmpv" --ondisk=${disk2} --size=1024 --grow --maxsize=2000000
volgroup centos --pesize=4096 pv.1 pv.2
...
logvol swap  --fstype="swap" --size=16064 --name=swap --vgname=centos
logvol /  --fstype="xfs" --grow --maxsize=2000000 --size=1024 --name=root --vgname=centos
...
etc...
```

**Comment by bgilbert** [comment]
In principle, it'd be good to support this.  There hasn't been much demand for it, though, since LVM is mostly useful for reconfiguring storage on already-running systems, and on Ignition-based systems you should probably just reprovision the node instead.

You can accomplish something similar with RAID linear mode.  Your example corresponds to something like this:

```yaml
variant: fcos
version: 1.4.0
storage:
  disks:
    # assuming /dev/vda is the install disk
    - device: /dev/vda
      partitions:
        # replace existing root partition with swap
        - label: swap
          number: 4
          wipe_partition_entry: true
          size_mib: 16384
        - label: root1
    - device: /dev/vdb
      wipe_table: true
      partitions:
        - label: root2
  raid:
    - name: md-root
      level: linear
      devices:
        - /dev/disk/by-partlabel/root1
        - /dev/disk/by-partlabel/root2
  filesystems:
    - device: /dev/disk/by-partlabel/swap
      format: swap
      wipe_filesystem: true
      # enable swap automatically
      with_mount_unit: true
    - device: /dev/md/md-root
      label: root
      format: xfs
      wipe_filesystem: true
```

However, there's currently a bug in the first-boot provisioning code (https://github.com/coreos/coreos-installer/pull/696) so `level: linear` won't work.  `level: raid0` is a reasonable workaround on FCOS 35+, but won't work on FCOS 34.  Fedora 34's mdadm doesn't include [this commit](https://git.kernel.org/pub/scm/utils/mdadm/mdadm.git/commit/?id=329dfc28debb58ffe7bd1967cea00fc583139aca), which is needed when creating RAID 0 volumes with non-uniform component sizes on modern kernels.
