### ISSUE TITLE
Notice if a filesystem overwrites a partitioned disk

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition#1397]
A common configuration error is to create a filesystem over a whole-disk device rather than the partition that was intended:

```yaml
variant: fcos
version: 1.4.0
storage:
  disks:
  - device: /dev/sdb
    wipe_table: false
    partitions:
    - label: data
  filesystems:
    - device: /dev/sdb
      path: /mnt
      format: ext4
      with_mount_unit: true
```

Add a warning if a `storage.filesystems.device` matches a `storage.disks.device`.
