### ISSUE TITLE
Cannot merge from remote source with static ip set manually

### ISSUE THREAD

**Issue by Kronk74** [coreos/ignition#1578]
# Bug #

Static IP address is not set before get ignition file from http source. 

## Operating System Version ##
RHCOS

## Ignition Version ##
3.3.0

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?

Deploy RHCOS on vmware cluster via ansible.

## Expected Behavior ##
The virtual machine must start is a static IP and after that, get the rest of ignition file from a http server.

## Actual Behavior ##
Do not set static IP and try to reach http server.

## Reproduction Steps ##

  1. Create an ignition file like this : 

```
{
  "ignition": {
    "config": {
      "merge": [
        {
          "source": "http://10.0.0.100/bootstrap.ign"
        }
      ]
    },
    "version": "3.3.0"
  },
  "storage": {
    "files": [
      {
        "path": "/etc/NetworkManager/conf.d/noauto.conf",
        "contents": {
          "compression": "",
          "source": "data:,%5Bmain%5D%0A%23%20Do%20not%20do%20automatic%20(DHCP%2FSLAAC)%20configuration%20on%20ethernet%20devices%0A%23%20with%20no%20other%20matching%20connections.%0Ano-auto-default%3D*%0A"
        },
        "mode": 420
      },
      {
        "path": "/etc/hostname",
        "contents": {
          "compression": "",
          "source": "data:,bootstrap.test.local"
        },
        "mode": 420
      },
      {
        "path": "/etc/NetworkManager/system-connections/ens192.nmconnection",
        "contents": {
          "compression": "gzip",
          "source": "data:;base64,<your-nmconnection-in-base64>"
        },
        "mode": 384
      }
    ]
  }
}
```

 2.  Deploy a virtual machine from a template (with ansible) : 

```
---
- name: "Create {{ vm.name }} virtual machines"
  community.vmware.vmware_guest:
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    folder: "{{ vm.folder }}"
    hostname: "{{ vcenter.url }}"
    datacenter: "{{ vm.datacenter }}"
    name: "{{ vm.name }}"
    state: "{{ vm.state }}"
    template: "{{ vm.template }}"
    disk:
      - size: "{{ vm.disk.size }}"
        type: "{{ vm.disk.type }}"
        datastore: "{{ vm.datastore }}"
    hardware:
      memory_mb: "{{ vm.hardware.memory_mb }}"
      num_cpus: "{{ vm.hardware.cpus }}"
    networks: "{{ vm.networks }}"
    cdrom:
      type: none
      state: absent
    vapp_properties: 
      - id: 'guestinfo.ignition.config.data'
        value: "{{ lookup('file', installer_working_dir + '/' + vm.name + '-first-boot.ign', errors='ignore') | b64encode | default (null) }}"
      - id: 'guestinfo.ignition.config.data.encoding' 
        value: 'base64'
  register: deployed_vm

- name: "Change {{ vm.name }} network configs"
  community.vmware.vmware_guest_network:
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    hostname: "{{ vcenter.url }}"
    datacenter: "{{ vm.datacenter }}"
    moid: "{{ deployed_vm.instance.moid }}"
    mac_address: "{{ deployed_vm.instance.hw_eth0.macaddress }}"
    network_name: "{{ vm.networks[0].name }}"
    connected: "{{ vm.network.connected | default (true) }}"
    start_connected: "{{ vm.network.start_connected | default (true) }}"
```

3. Wait an read message error message 

`Get error : Get http://10.0.0.100/bootstrap.ign dial tcp 10.0.0.100:80 connect: network us unreachable`  

## Other Information ##

When I remove the line with ignition merge, The machine is configured with good ip address and hostname.
