### ISSUE TITLE
Persistent /var on RAID: What am I doing wrong?

### ISSUE THREAD

**Issue by runiq** [coreos/ignition#1741]
# Bug #

I want to use [mirrored boot disks](https://coreos.github.io/butane/examples/#mirrored-boot-disk), but I want to put `/var` on a separate partition **persistently**. Because [persistent RAID partitions don't seem to be supported out of the box](https://github.com/coreos/ignition/issues/579), I'm following the advice in [this issue(https://github.com/coreos/ignition/issues/579#issuecomment-403688642) to create the RAID+filesystem for `/var` in my own Systemd unit. While this works in principle, it seems Ignition requires that my `/var` filesystem be available while it is running. Is this somehow possible to achieve?

## Operating System Version ##

Fedora CoreOS 38.20231002.3.1

## Ignition Version ##

3.4.0

## Environment ##

Libvirt on Fedora Kinoite 38.20231103.0

## Expected Behavior ##

- `/var` is populated correctly
- No failed units
- `core` user has a home directory

## Actual Behavior ##

It looks like my `/var` filesystem _must_ be available during the Ignition run for the system to be functional. After Ignition runs its course (without apparent error), my `/var` only seems to be 'half-populated,' so to speak. These are the issues I see:

- coreos-populate-lvmdevices.service fails because it cannot touch its stamp file in `/var/lib` (presumably because the `lib` directory does not exist
- systemd-random-seed fails because it cannot find `/var/lib/systemd`
- The journal is not persistent
- The `core` user ends up in `/` because its home directory does not exist
- Zincati keeps telling me to reboot because it has scheduled an update

## Reproduction Steps ##

Use the following Butane file:

<details><summary><code>repro.bu</code></summary>

```yaml
variant: "fcos"
version: "1.5.0"
boot_device:
  mirror:
    devices:
      - "/dev/disk/by-id/virtio-root-1"
      - "/dev/disk/by-id/virtio-root-2"
systemd:
  units:
    - name: "serial-getty@ttyS0.service"
      dropins:
        - name: "autologin-core.conf"
          contents: |
            [Service]
            # Override Execstart in main unit
            ExecStart=
            # Add new Execstart with `-` prefix to ignore failure
            ExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM
            TTYVTDisallocate=no
    - name: "create-var.service"
      enabled: true
      contents: |
        [Unit]
        Description=Create md-var RAID and var filesystem
        DefaultDependencies=no

        # We 'slot' this in between the component devices of the RAID volume
        # and the /var mount:
        After=local-fs-pre.target
        After=dev-disk-by\x2dpartlabel-var\x2d1.device
        After=dev-disk-by\x2dpartlabel-var\x2d2.device
        Before=systemd-fsck@dev-md-md\x2dvar.service
        Before=var.mount

        # The RAID itself and the filesystem on it should NOT yet exist for this
        # unit to run
        ConditionPathExists=!/dev/md/md-var
        ConditionPathExists=!/dev/disk/by-label/var

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/bash -c 'echo yes | /usr/sbin/mdadm --create md-var \
        	--verbose \
        	--homehost=any \
        	--level=raid1 \
        	--raid-devices=2 \
        	/dev/disk/by-partlabel/var-1 \
        	/dev/disk/by-partlabel/var-2'
        ExecStart=/usr/bin/bash -c 'ls -l /var 1>&2'
        # mkfs.xfs fails if there is already a filesystem present on the device
        ExecStart=/usr/sbin/mkfs.xfs -Lvar /dev/md/md-var

        [Install]
        WantedBy=dev-md-md\x2dvar.device
    - name: "var.mount"
      enabled: false
      contents: |
        [Unit]
        Requires=systemd-fsck@dev-md-md\x2dvar.service
        After=systemd-fsck@dev-md-md\x2dvar.service

        [Mount]
        What=/dev/md/md-var
        Where=/var
        Type=xfs
        Options=defaults,strictatime,lazytime,prjquota

        [Install]
        RequiredBy=local-fs.target
storage:
  disks:
    - device: "/dev/disk/by-id/virtio-root-1"
      partitions:
        - label: "esp-1"
          wipe_partition_entry: true
        - label: "boot-1"
          wipe_partition_entry: true
        - label: "root-1"
          size_mib: 8400
          wipe_partition_entry: true
        - label: "var-1"
          wipe_partition_entry: false
          type_guid: "A19D880F-05FC-4D3B-A006-743F0F84911E"
    - device: "/dev/disk/by-id/virtio-root-2"
      partitions:
        - label: "esp-2"
          wipe_partition_entry: true
        - label: "boot-2"
          wipe_partition_entry: true
        - label: "root-2"
          size_mib: 8400
          wipe_partition_entry: true
        - label: "var-2"
          wipe_partition_entry: false
          type_guid: "A19D880F-05FC-4D3B-A006-743F0F84911E"
  filesystems:
    - device: "/dev/md/md-boot"
      wipe_filesystem: true
    - device: "/dev/md/md-root"
      wipe_filesystem: true
      format: "xfs"
```
</details>

Compile it to Ignition:

<details><summary><code>repro.ign</code></summary>

```json
{
  "ignition": {
    "version": "3.4.0"
  },
  "storage": {
    "disks": [
      {
        "device": "/dev/disk/by-id/virtio-root-1",
        "partitions": [
          {
            "label": "bios-1",
            "sizeMiB": 1,
            "typeGuid": "21686148-6449-6E6F-744E-656564454649"
          },
          {
            "label": "esp-1",
            "sizeMiB": 127,
            "typeGuid": "C12A7328-F81F-11D2-BA4B-00A0C93EC93B",
            "wipePartitionEntry": true
          },
          {
            "label": "boot-1",
            "sizeMiB": 384,
            "wipePartitionEntry": true
          },
          {
            "label": "root-1",
            "sizeMiB": 8400,
            "wipePartitionEntry": true
          },
          {
            "label": "var-1",
            "typeGuid": "A19D880F-05FC-4D3B-A006-743F0F84911E",
            "wipePartitionEntry": false
          }
        ],
        "wipeTable": true
      },
      {
        "device": "/dev/disk/by-id/virtio-root-2",
        "partitions": [
          {
            "label": "bios-2",
            "sizeMiB": 1,
            "typeGuid": "21686148-6449-6E6F-744E-656564454649"
          },
          {
            "label": "esp-2",
            "sizeMiB": 127,
            "typeGuid": "C12A7328-F81F-11D2-BA4B-00A0C93EC93B",
            "wipePartitionEntry": true
          },
          {
            "label": "boot-2",
            "sizeMiB": 384,
            "wipePartitionEntry": true
          },
          {
            "label": "root-2",
            "sizeMiB": 8400,
            "wipePartitionEntry": true
          },
          {
            "label": "var-2",
            "typeGuid": "A19D880F-05FC-4D3B-A006-743F0F84911E",
            "wipePartitionEntry": false
          }
        ],
        "wipeTable": true
      }
    ],
    "filesystems": [
      {
        "device": "/dev/disk/by-partlabel/esp-1",
        "format": "vfat",
        "label": "esp-1",
        "wipeFilesystem": true
      },
      {
        "device": "/dev/disk/by-partlabel/esp-2",
        "format": "vfat",
        "label": "esp-2",
        "wipeFilesystem": true
      },
      {
        "device": "/dev/md/md-boot",
        "format": "ext4",
        "label": "boot",
        "wipeFilesystem": true
      },
      {
        "device": "/dev/md/md-root",
        "format": "xfs",
        "label": "root",
        "wipeFilesystem": true
      }
    ],
    "raid": [
      {
        "devices": [
          "/dev/disk/by-partlabel/boot-1",
          "/dev/disk/by-partlabel/boot-2"
        ],
        "level": "raid1",
        "name": "md-boot",
        "options": [
          "--metadata=1.0"
        ]
      },
      {
        "devices": [
          "/dev/disk/by-partlabel/root-1",
          "/dev/disk/by-partlabel/root-2"
        ],
        "level": "raid1",
        "name": "md-root"
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "dropins": [
          {
            "contents": "[Service]\n# Override Execstart in main unit\nExecStart=\n# Add new Execstart with `-` prefix to ignore failure\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM\nTTYVTDisallocate=no\n",
            "name": "autologin-core.conf"
          }
        ],
        "name": "serial-getty@ttyS0.service"
      },
      {
        "contents": "[Unit]\nDescription=Create md-var RAID and var filesystem\nDefaultDependencies=no\n\n# We 'slot' this in between the component devices of the RAID volume\n# and the /var mount:\nAfter=local-fs-pre.target\nAfter=dev-disk-by\\x2dpartlabel-var\\x2d1.device\nAfter=dev-disk-by\\x2dpartlabel-var\\x2d2.device\nBefore=systemd-fsck@dev-md-md\\x2dvar.service\nBefore=var.mount\n\n# The RAID itself and the filesystem on it should NOT yet exist for this\n# unit to run\nConditionPathExists=!/dev/md/md-var\nConditionPathExists=!/dev/disk/by-label/var\n\n[Service]\nType=oneshot\nRemainAfterExit=yes\nExecStart=/usr/bin/bash -c 'echo yes | /usr/sbin/mdadm --create md-var \\\n\t--verbose \\\n\t--homehost=any \\\n\t--level=raid1 \\\n\t--raid-devices=2 \\\n\t/dev/disk/by-partlabel/var-1 \\\n\t/dev/disk/by-partlabel/var-2'\nExecStart=/usr/bin/bash -c 'ls -l /var 1\u003e\u00262'\n# mkfs.xfs fails if there is already a filesystem present on the device\nExecStart=/usr/sbin/mkfs.xfs -Lvar /dev/md/md-var\n\n[Install]\nWantedBy=dev-md-md\\x2dvar.device\n",
        "enabled": true,
        "name": "create-var.service"
      },
      {
        "contents": "[Unit]\nRequires=systemd-fsck@dev-md-md\\x2dvar.service\nAfter=systemd-fsck@dev-md-md\\x2dvar.service\n\n[Mount]\nWhat=/dev/md/md-var\nWhere=/var\nType=xfs\nOptions=defaults,strictatime,lazytime,prjquota\n\n[Install]\nRequiredBy=local-fs.target\n",
        "enabled": false,
        "name": "var.mount"
      }
    ]
  }
}
```
</details>

Create the VM using libvirt (adapted [from the documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-libvirt/)):

```bash
set -euxo pipefail

readonly image="$(podman run --rm --init \
	--security-opt label=disable \
	-v ./:/data \
	-w /data \
	quay.io/coreos/coreos-installer:release \
		download --stream stable -p qemu -f qcow2.xz --decompress)"
mv "$image" fcos.qcow2
rm -f "${image}.sig"

IGNITION_CONFIG="$PWD/repro.ign"
IMAGE="$PWD/fcos.qcow2"
chcon --verbose --type svirt_home_t ${IGNITION_CONFIG} ${IMAGE}
virt-install \
	--connect=qemu:///session \
	--name=repro \
	--vcpus="2" \
	--memory="8192" \
	--boot=uefi \
	--graphics=none \
	--disk="path=root-1.qcow2,size=12,serial=root-1,backing_store=${IMAGE}" \
	--disk="path=root-2.qcow2,size=12,serial=root-2" \
	--os-variant="fedora-coreos-stable" \
	--qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${IGNITION_CONFIG}" \
	--import
```
