### ISSUE TITLE
Support for encrypted inline file content

### ISSUE THREAD

**Issue by soubinan** [coreos/ignition#1767]
# Feature Request #

## Environment ##

What hardware/cloud provider/hypervisor is being used to run Ignition?
I use cores on bare metal, on KVM and XEN virtual machines powered by Cloudstack private cloud

## Desired Feature ##

It would be great to be able to encypt an inline file content for file with credentals configuration for example (the same we are doing on users passwords but for file content

Example of what it could looks like:
```yaml
...
storage:
  disks:
    ...
  directories:
    ...
  files:
    - path: /etc/my_app/my_app.conf
      mode: 0400
      contents:
        inline: |
          algo-$y$j9T$GHWl3yQUIHdkwYhEk8R8J.$cYf8nRRKA92jvQBtxnPmKYmihvzTXRW5B6ETCCXKPI2
        ...
...
```
