### ISSUE TITLE
Disk label changes on reboot

### ISSUE THREAD

**Issue by bkrajendra** [coreos/ignition#1843]
# Bug #
I understand this might not be directly related to CoreOS setup, but issue i am facing is related to the way setup works.

## Operating System Version ##
Fedora CoreOS: v39.2024030

## Ignition Version ##
version: 1.5.0
## Environment ##
What hardware/cloud provider/hypervisor is being used to run Ignition?
Bare Metal - Dell PowerEdge server

## Expected Behavior ##
Setup should work as documented.
The virtual disk name should not change on reboot.
## Actual Behavior ##
I am installing a Fedora CoreOS 39 on a bare metal system (PowerEdge server) through a iDRac interface.
The install step works ok, but after reboot the virtual disk name changes which fail the setup.

## Reproduction Steps ##
1. First I am botting into Fedora LiveISO (virtual cd-rom) and perform the install step:
```coreos-installer install /dev/sda --ignition-url http://filepath.ign```
once file system is copied, it reboots to perform the installation.
at this stage the lsblk shows:
![error1](https://github.com/coreos/ignition/assets/994083/a0f0e873-9a2e-4e89-a200-d465a5943084)

2. After reboot, when installation proceeds, it throws error related to disk not found.
My issue is when I first time boot the system with liveCD, it shows up my two-disk label as **sda and sdb**, but when system reboots for second phase those disk label changes to **sdb and sdc**.
The reason is this step1 creates some temporary partition which sits at sda.
This how lsblk looks after reboot:
![error2](https://github.com/coreos/ignition/assets/994083/2003e470-1cb2-4f33-afe0-99ae482de089)

Because of this, setup fails with error "Problem opening /dev/sda"

How can I make sure the disk name does not change on reboot.
What wrong i am doing here?

## Ignition file content
```
variant: fcos
version: 1.5.0
passwd:
  users:
    - name: myuser
      groups:
        - docker
        - wheel
        - sudo
      # password_hash: hash
      ssh_authorized_keys:
        - ssh-key
storage: 
  disks: 
    - device: /dev/sdb
      wipe_table: true
      partitions:
        - label: root
          type_guid: 0fc63daf-8483-4772-8e79-3d69d8477de4
          size_mib: 200000

    - device: /dev/sda
      wipe_table: true
      partitions:
        - label: data2
          number: 1
          size_mib: -1
          type_guid: 0fc63daf-8483-4772-8e79-3d69d8477de4

  filesystems:
    - device: /dev/disk/by-partlabel/data1
      path: /data1
      label: data1
      format: xfs
      wipe_filesystem: true
    - device: /dev/disk/by-partlabel/data2
      path: /data2
      label: data2
      format: xfs
      wipe_filesystem: true

```

**Comment by ananthb** [comment]
Let's clear up some terminology first. sda, sub, etc are disk _names_ and not labels.

You've actually used partition labels in your ignition correctly, and those are not directly related to disk names.

Instead of specifying disks by name can you try specifying them by id instead?

Like this:

```yaml
...
storage: 
  disks: 
    - device: /dev/disk/by-id/disk-id-goes-here
      wipe_table: true
      partitions:
        - label: root
          type_guid: 0fc63daf-8483-4772-8e79-3d69d8477de4
          size_mib: 200000
...
```
