### ISSUE TITLE
Ignition Config not working as expected on VMWare Fusion 

### ISSUE THREAD

**Issue by coreosbot** [coreos/ignition#584]
**Issue by @thomasbell1985**
***
# Issue Report #

I am attempting to use the ignition config to configure the authorized ssh keys for the core user using guest info for vmware. I am following the docs found [here](https://coreos.com/os/docs/latest/booting-on-vmware.html#vmware-guestinfo-interface). It does not appear to be working correctly, i.e. the authorized ssh keys are not being set. 

### Container Linux Version ###

Below is the os-release information

<img width="568" alt="screen shot 2017-11-07 at 7 16 25 am" src="https://user-images.githubusercontent.com/5281642/32493402-b5dd06f6-c38b-11e7-899f-d2a185d66503.png">

BUG_REPORT_URL="https://issues.coreos.com"

### Environment ###

I am using VMWare Fusion Pro 10.0.1 for the mac 

### Expected Behavior ###

When setting the following parameters with the correct ignition config:

```
guestinfo.coreos.config.data = ""
guestinfo.coreos.config.data.encoding = "base64"
```

I expect the parameters specified to be set on the machine at boot time. I am attempting to set the ssh_authorized keys for the core user. 
### Actual Behavior ###

The machine boots, but no authorized keys are set for the core user. running the following command:

```
$: ls .ssh/
```
shows an empty directory.

### Reproduction Steps ###

  1. Create a ignition config.yaml that looks like this:
```
passwd:
  users:
    - name: core
    - ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLu+/5DffWK2Olj1SdlG335yKdRtUVq6WKhMoee0lF4UaqaXPXJx2R2wD869QcK+ys2AJshCpH/sPVKqFZrvtagROlMND/y8JAtfdlamILwUve7gGisSz5a4wOJIV4MQfzFC29aiGcHasBDDu4XyWICeWCa8vhgqeAAm2VsdHvMbqSbOWLIHYj5JxMBE13/e3Y9TuBiBYQegW4GFCVj3GCO7jrI+hF6RkTBorHhP8DeoiB7zGHwVbVn5iHgEfUpJKqXCVL+JI/7TZ0DnCKGvF3ibn8B6ZrUO43jzNAERif44aAf39Dib4fNgR7RuVh6Ss+QsiuZlBE5XmJeUGaUhtumaT1Md5jd5m2uKRlt7gJECl6376hFdUDIJmK8oZQsGqwyWrzHGi8YrOtYpUladIgTS9JGnmfoTretxTfmdUsNCMnFB8hzPLNp6CtZL+ibSJIQxhX5bbLDj+V3Teeb4S+iP/14Hk2DzA3ItzFxYRudb6xeI8xfcRYiH8W+gN1zPJ3ppWrB8KgXxvYxyd/rwDs6uwU6nu8zXJRCoz0ltLL9hPmyZGsH/3CX4W0m99L8nPcakn/WSvDTfYJJD6P2o8lI4DbjF9vl3J3d4muiIQMFTvuRVTTw6gkkX9zJKzdL34jTXuYvtKy9iNVsIw7f98L1tTnCzNzRh1LobTSJUXrbw== k8s-cluster-user@mydomain.com"        
```
  2. I then transpile using the latest version of the ignition transpile by running the following command:

```
ct --in-file path/to/ignition-config.yaml --out-file path/to/ignition-config.json
```
  3. Base 64 encode the ignition-config.json using the following command

```
base64  path/to/ignition-config.json
```
which produces this output:

```
eyJpZ25pdGlvbiI6eyJjb25maWciOnt9LCJ0aW1lb3V0cyI6e30sInZlcnNpb24iOiIyLjEuMCJ9LCJuZXR3b3JrZCI6e30sInBhc3N3ZCI6eyJ1c2VycyI6W3sibmFtZSI6ImNvcmUifSx7InNzaEF1dGhvcml6ZWRLZXlzIjpbInNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQ0FRREx1Ky81RGZmV0syT2xqMVNkbEczMzV5S2RSdFVWcTZXS2hNb2VlMGxGNFVhcWFYUFhKeDJSMndEODY5UWNLK3lzMkFKc2hDcEgvc1BWS3FGWnJ2dGFnUk9sTU5EL3k4SkF0ZmRsYW1JTHdVdmU3Z0dpc1N6NWE0d09KSVY0TVFmekZDMjlhaUdjSGFzQkREdTRYeVdJQ2VXQ2E4dmhncWVBQW0yVnNkSHZNYnFTYk9XTElIWWo1SnhNQkUxMy9lM1k5VHVCaUJZUWVnVzRHRkNWajNHQ083anJJK2hGNlJrVEJvckhoUDhEZW9pQjd6R0h3VmJWbjVpSGdFZlVwSktxWENWTCtKSS83VFowRG5DS0d2RjNpYm44QjZaclVPNDNqek5BRVJpZjQ0YUFmMzlEaWI0Zk5nUjdSdVZoNlNzK1FzaXVabEJFNVhtSmVVR2FVaHR1bWFUMU1kNWpkNW0ydUtSbHQ3Z0pFQ2w2Mzc2aEZkVURJSm1LOG9aUXNHcXd5V3J6SEdpOFlyT3RZcFVsYWRJZ1RTOUpHbm1mb1RyZXR4VGZtZFVzTkNNbkZCOGh6UExOcDZDdFpMK2liU0pJUXhoWDViYkxEaitWM1RlZWI0UytpUC8xNEhrMkR6QTNJdHpGeFlSdWRiNnhlSTh4ZmNSWWlIOFcrZ04xelBKM3BwV3JCOEtnWHh2WXh5ZC9yd0RzNnV3VTZudTh6WEpSQ296MGx0TEw5aFBteVpHc0gvM0NYNFcwbTk5TDhuUGNha24vV1N2RFRmWUpKRDZQMm84bEk0RGJqRjl2bDNKM2Q0bXVpSVFNRlR2dVJWVFR3Nmdra1g5ekpLemRMMzRqVFh1WXZ0S3k5aU5Wc0l3N2Y5OEwxdFRuQ3pOelJoMUxvYlRTSlVYcmJ3PT0gazhzLWNsdXN0ZXItdXNlckBteWRvbWFpbi5jb20iXX1dfSwic3RvcmFnZSI6e30sInN5c3RlbWQiOnt9fQ==
```

The decoded output looks like this:

```
{"ignition":{"config":{},"timeouts":{},"version":"2.1.0"},"networkd":{},"passwd":{"users":[{"name":"core"},{"sshAuthorizedKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLu+/5DffWK2Olj1SdlG335yKdRtUVq6WKhMoee0lF4UaqaXPXJx2R2wD869QcK+ys2AJshCpH/sPVKqFZrvtagROlMND/y8JAtfdlamILwUve7gGisSz5a4wOJIV4MQfzFC29aiGcHasBDDu4XyWICeWCa8vhgqeAAm2VsdHvMbqSbOWLIHYj5JxMBE13/e3Y9TuBiBYQegW4GFCVj3GCO7jrI+hF6RkTBorHhP8DeoiB7zGHwVbVn5iHgEfUpJKqXCVL+JI/7TZ0DnCKGvF3ibn8B6ZrUO43jzNAERif44aAf39Dib4fNgR7RuVh6Ss+QsiuZlBE5XmJeUGaUhtumaT1Md5jd5m2uKRlt7gJECl6376hFdUDIJmK8oZQsGqwyWrzHGi8YrOtYpUladIgTS9JGnmfoTretxTfmdUsNCMnFB8hzPLNp6CtZL+ibSJIQxhX5bbLDj+V3Teeb4S+iP/14Hk2DzA3ItzFxYRudb6xeI8xfcRYiH8W+gN1zPJ3ppWrB8KgXxvYxyd/rwDs6uwU6nu8zXJRCoz0ltLL9hPmyZGsH/3CX4W0m99L8nPcakn/WSvDTfYJJD6P2o8lI4DbjF9vl3J3d4muiIQMFTvuRVTTw6gkkX9zJKzdL34jTXuYvtKy9iNVsIw7f98L1tTnCzNzRh1LobTSJUXrbw== k8s-cluster-user@mydomain.com"]}]},"storage":{},"systemd":{}}
```

I have validated this config [here](https://coreos.com/validate/) which results in the following output:

<img width="805" alt="screen shot 2017-11-07 at 7 28 56 am" src="https://user-images.githubusercontent.com/5281642/32493885-84f73938-c38d-11e7-99fb-f36bb098552c.png">

### Other Information ###

If I base64 encode a cloud-config.yml file and put it in the guest info parameter things work as expected, but not with the ignition config
