### ISSUE TITLE
retry for ftp/tftp

### ISSUE THREAD

**Issue by bcg62** [coreos/ignition#711]
Retry functionality exists for http/https, but not ftp/tftp

https://coreos.com/ignition/docs/latest/operator-notes.html#http-backoff-and-retry

This can create flaky results if boot ordering, or delays in network initialization throw off ignition on its first attempt to grab configuration.

https://github.com/coreos/ignition-dracut/issues/41

**Comment by bcg62** [comment]
is there a specific reason ftp is excluded? Aside from the config.url cmdline property i see it also cannot be used for remote files.

IE:
```
    - path: /usr/local/bin/test.sh
      filesystem: root
      contents:
        remote:
          url: ftp://.....
      mode: 755

```
$ ct -in-file  ./test
error at line 264, column 14
invalid url scheme
```
