### ISSUE TITLE
btrfs filesystems cannot be specifed with mutlple devices

### ISSUE THREAD

**Issue by nickbreen** [coreos/ignition#815]
# Feature Request #

Support multiple devices for btrfs filesystems in *.ign configuration.

## Environment ##

Bare metal, PXE boot.

## Desired Feature ##

Essentially to have this configuration supported:

```yaml
storage:
  disks:
    - device: /dev/sda
      wipe_table: false
      partitions:
        - label: srva
          number: 1
          start: 0
          size: 0
          type_guid: 3B8F8425-20E0-4F3B-907F-1A25A76F98E8 # Linux /srv
    - device: /dev/sdb
      wipe_table: false
      partitions:
        - label: srvb
          number: 1
          start: 0
          size: 0
          type_guid: 3B8F8425-20E0-4F3B-907F-1A25A76F98E8 # Linux /srv

  filesystems:
    - name: srv
      mount:
        device: [ /dev/disk/by-partlabel/srva, /dev/disk/by-partlabel/srvb ]
        format: btrfs
        wipe_filesystem: false
        label: SRV
```

## Other Information ##

This works perfectly now, but with only single device support.
