### ISSUE TITLE
support device: rootdevice: true

### ISSUE THREAD

**Issue by cgwalters** [coreos/ignition#845]
I want to make it easy and ergonomic to add a `/var` (and other partitions) to the boot device.  Today one can write `device: /dev/vda` but that makes it inherently non-portable.  This isn't a big deal, but let's add support for something like:

```
storage:
  disks:
    - bootdevice: true
      partitions:
        - label: var
          size_mib: 0
          number: 0
```

Here `bootdevice: true` means to add a partition to the device from which we booted (the one with `label=root`).
