### ISSUE TITLE
Unable to resize an existing partition

### ISSUE THREAD

**Issue by jlebon** [coreos/ignition#924]
I'm trying to write an fcct to resize the root partition to e.g. 5G and leave the rest unassigned (let's forget about `coreos-growpart.service` for now). Here's what I'm using:

```
storage:
  disks:
  - device: /dev/vda
    wipe_table: false
    partitions:
    - number: 4
      size_mib: 5000
      start_mib: 0
      label: root
```

This gives me an error:

```
Ignition failed: create partitions failed: Partition 4 didn't match: size did not match (specified 10240000, got 4405248)
```

This is needed so that we can grow the rootfs a bit more before trapping it behind e.g. a `/var` partition. See thread starting at https://github.com/coreos/coreos-assembler/pull/924#issuecomment-559258940.
