### ISSUE TITLE
Ignition fails to verify partition size in qemu

### ISSUE THREAD

**Issue by AdamZ** [coreos/ignition#984]
# Bug #

I'm trying to mount an external partition on fcOS in addition to the root fs.

## Operating System Version ##
fcOS stable (fedora-coreos-31.20200420.3.0-qemu.x86_64)

## Ignition Version ##
Ignition 2.2.1

## Environment ##

qemu, controlled by virt-manager

## Reproduction Steps ##

An empty disk image was created using the following commands:
```
qemu-img create -f qcow2 /var/lib/libvirt/images/maildir.qcow2 2048M
virt-format -a /var/lib/libvirt/images/maildir.qcow2 --filesystem=ext3 --partition=gpt --label=vmail-dir
```

Relevant part of the FCC file:
```yaml
storage:
  disks:
    -
      device: /dev/disk/by-id/virtio-VIRT-mail-disk
      wipe_table: false
      partitions:
        -
          label: vmail-dir
          number: 1
          size_mib: 0
          start_mib: 0
          type_guid: 0FC63DAF-8483-4772-8E79-3D69D8477DE4
          wipe_partition_entry: false
  filesystems:
    -
      path: /var/vmail
      device: /dev/disk/by-label/vmail-dir
      format: ext4
      wipe_filesystem: false
      label: vmail-dir
```

## Expected Behavior ##

Given that `size_mib` and `start_mib` are both 0, and there is a single partition on the virtual disk, Ignition should mount the partition with no errors.

## Actual Behavior ##

Ignition fails to verify the size of the partition, giving the error:
```
disks: createPartitions: op(2): [failed]   partitioning "/run/ignition/dev_aliases/dev/disk/by-id/virtio-VIRT-mail-disk": Partition 1 didn't match: size did not match (specified 4194143, got 4194049)
Ignition failed: create partitions failed: Partition 1 didn't match: size did not match (specified 4194143, got 4194049)
```

## Other Information ##

Here's the entire ignition output, minus the dump of the config file:
<details><summary>Entire output</summary>

```
-------------------------------------------------------------------------------
Ignition has failed. Please ensure your config is valid. Note that only Ignition spec
v3.0.0+ configs are accepted.
A CLI validation tool to check this called ignition-validate can be downloaded from GitHub:
    https://github.com/coreos/ignition/releases
Here are the Ignition logs:
Ignition 2.2.1
Stage: fetch
reading system config file "/usr/lib/ignition/base.ign"
parsing config with SHA512: ff6a5153be363997e4d5d3ea8cc4048373a457c48c4a5b134a08a30aacd167c1e0f099f0bdf1e24c99ad180628cd02b767b863b5fe3a8fce3fe1886847eb8e2e
parsed url from cmdline: ""
no config URL provided
reading system config file "/usr/lib/ignition/user.ign"
no config at "/usr/lib/ignition/user.ign"
op(1): [started]  loading QEMU firmware config module
op(1): executing: "modprobe" "qemu_fw_cfg"
op(1): [finished] loading QEMU firmware config module
parsing config with SHA512: 7b526be6b025d93fd45e89200872f44a8d6bf5d8cfc9ace07db92d3f02a9b1331abf023f4387624fb593a963cc2e5efc20d659675d9b9a70e94c9593d1f09729
fetch: fetch complete
fetch: fetch passed
Ignition finished successfully
Ignition 2.2.1
Stage: disks
reading system config file "/usr/lib/ignition/base.ign"
parsing config with SHA512: ff6a5153be363997e4d5d3ea8cc4048373a457c48c4a5b134a08a30aacd167c1e0f099f0bdf1e24c99ad180628cd02b767b863b5fe3a8fce3fe1886847eb8e2e
disks: createPartitions: op(1): [started]  waiting for devices [/dev/disk/by-id/virtio-VIRT-mail-disk]
disks: createPartitions: op(1): [finished] waiting for devices [/dev/disk/by-id/virtio-VIRT-mail-disk]
disks: createPartitions: created device alias for "/dev/disk/by-id/virtio-VIRT-mail-disk": "/run/ignition/dev_aliases/dev/disk/by-id/virtio-VIRT-mail-disk" -> "/dev/vdb"
disks: createPartitions: op(2): [started]  partitioning "/run/ignition/dev_aliases/dev/disk/by-id/virtio-VIRT-mail-disk"
disks: createPartitions: op(2): op(3): [started]  reading partition table of "/run/ignition/dev_aliases/dev/disk/by-id/virtio-VIRT-mail-disk"
disks: createPartitions: op(2): op(3): [finished] reading partition table of "/run/ignition/dev_aliases/dev/disk/by-id/virtio-VIRT-mail-disk"
disks: createPartitions: op(2): running sgdisk with options: [--pretend --delete=1 --new=1:0:+0 --typecode=1:0FC63DAF-8483-4772-8E79-3D69D8477DE4 --info=1 /run/ignition/dev_aliases/dev/disk/by-id/virtio-VIRT-mail-disk]
disks: createPartitions: op(2): [failed]   partitioning "/run/ignition/dev_aliases/dev/disk/by-id/virtio-VIRT-mail-disk": Partition 1 didn't match: size did not match (specified 4194143, got 4194049)
Ignition failed: create partitions failed: Partition 1 didn't match: size did not match (specified 4194143, got 4194049)
```
</details>
